# =PermissionRequired= (default: false)
# 'veinminer.mining' 권한이 있는 플레이어만 사용 가능하게 함
PermissionRequired: false
# =OnlyAtSneaking= (default: true)
# 웅크렸을 때에만 연쇄파괴함
OnlyAtSneaking: true
# =Ticking= (default: 1)
# 한 틱당 블럭이 파괴 되는 개수, 0으로 하면 계산된 모든 블럭이 한번에 파괴됨
# 이 수치를 0으로 하거나 너무 크게 할 경우 플레이어에게 과도한 그래픽 처리 렉을 유발할 수 있음
Ticking: 1
# =MaxChain= (default: 256)
# 블럭 연쇄파괴의 최대 개수
# 이 수치를 너무 크게 할 경우 서버에 과도한 계산 처리 렉을 유발할 수 있음
MaxChain: 256
# =TeleportDrops= (default: false)
# 블럭이 파괴되고 떨어지는 아이템을 파괴자에게 즉시 전달
TeleportDrops: false
# =BreakSimilars= (default: true)
# 유사한 블럭(예: 철 광석-심층암 철 광석)을 함께 파괴, 유사한 블럭 설정은 밑에서 설정 가능
BreakSimilars: true
# =BreakDiagonal= (default: 0)
# 대각선 방향으로도 블럭을 연쇄적으로 파괴
# 0: 면이 닿아 있어야 함(대각선 계산 안함)
# 1: 모서리가 닿아 있어야 함
# 2: 꼭짓점이 닿아 있어야 함
BreakDiagonal: 0
# =OverrideBlacklist= (default: true)
# Blacklist에 있는 블럭은 연쇄파괴되지 못하게 함
OverrideBlacklist: true
# =IndividualWhitelist= (default: false)
# 연쇄파괴할 아이템 등록을 개인마다 다르게 설정 가능(미구현 기능)
IndividualWhitelist: false
# =Whitelist=
# IndividualWhitelist가 false일 때 연쇄파괴되는 블럭
Whitelist:
  - COAL_ORE
  - IRON_ORE
  - COPPER_ORE
  - GOLD_ORE
  - LAPIS_ORE
  - REDSTONE_ORE
  - EMERALD_ORE
  - DIAMOND_ORE
  - DEEPSLATE_COAL_ORE
  - DEEPSLATE_IRON_ORE
  - DEEPSLATE_COPPER_ORE
  - DEEPSLATE_GOLD_ORE
  - DEEPSLATE_LAPIS_ORE
  - DEEPSLATE_REDSTONE_ORE
  - DEEPSLATE_EMERALD_ORE
  - DEEPSLATE_DIAMOND_ORE
  - RAW_IRON_BLOCK
  - RAW_COPPER_BLOCK
  - RAW_GOLD_BLOCK
  - NETHER_QUARTZ_ORE
  - NETHER_GOLD_ORE
  - ANCIENT_DEBRIS
# =Blacklist=
# OverrideBlacklist가 true일 때, 해당 블럭들은 Whitelist나 Similars에 있더라도 연쇄파괴되지 못함
Blacklist:
  - GRASS_BLOCK
  - DIRT
  - STONE
  - DEEPSLATE
  - SAND
  - ICE
  - PACKED_ICE
  - SNOW
  - SNOW_BLOCK
  - POWDER_SNOW
  - NETHERRACK
  - SOUL_SAND
  - SOUL_SOIL
  - CRIMSON_NYLIUM
  - WARPED_NYLIUM
  - END_STONE
  - BEDROCK
# =Similars=
# 유사한 블럭 설정
Similars:
  - - COAL_ORE
    - DEEPSLATE_COAL_ORE
  - - IRON_ORE
    - DEEPSLATE_IRON_ORE
  - - COPPER_ORE
    - DEEPSLATE_COPPER_ORE
  - - GOLD_ORE
    - DEEPSLATE_GOLD_ORE
  - - LAPIS_ORE
    - DEEPSLATE_LAPIS_ORE
  - - REDSTONE_ORE
    - DEEPSLATE_REDSTONE_ORE
  - - EMERALD_ORE
    - DEEPSLATE_EMERALD_ORE
  - - DIAMOND_ORE
    - DEEPSLATE_DIAMOND_ORE
